# Generated by Django 5.1.4 on 2026-06-28 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('capacity', models.PositiveSmallIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('host', models.CharField(blank=True, max_length=160)),
                ('event_date', models.DateField()),
                ('covers', models.PositiveSmallIntegerField(default=50)),
                ('package_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('tentative', 'Tentative'), ('confirmed', 'Confirmed'), ('completed', 'Completed')], default='tentative', max_length=12)),
                ('billed', models.BooleanField(default=False)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='banquets.functionspace')),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
    ]
