# Generated by Django 5.1.15 on 2026-06-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banquets', '0002_event_contact_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='food_covers',
            field=models.PositiveSmallIntegerField(default=0, help_text='approx. plates to cater'),
        ),
        migrations.AddField(
            model_name='event',
            name='food_pref',
            field=models.CharField(blank=True, help_text='veg | nonveg | both', max_length=10),
        ),
    ]
