# Generated by Django 5.1.15 on 2026-06-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banquets', '0003_event_food_covers_event_food_pref'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='beo_status',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
