# Generated by Django 5.1.15 on 2026-07-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banquets', '0004_event_beo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='food_nonveg',
            field=models.PositiveSmallIntegerField(default=0, help_text='approx. non-veg plates'),
        ),
        migrations.AddField(
            model_name='event',
            name='food_veg',
            field=models.PositiveSmallIntegerField(default=0, help_text='approx. veg plates'),
        ),
        migrations.AlterField(
            model_name='event',
            name='food_covers',
            field=models.PositiveSmallIntegerField(default=0, help_text='approx. plates to cater (veg + nonveg)'),
        ),
    ]
