# Generated by Django 5.1.15 on 2026-07-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banquets', '0005_event_food_nonveg_event_food_veg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, help_text='event end time', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, help_text='event start time', null=True),
        ),
    ]
