# Generated by Django 5.1.15 on 2026-07-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banquets', '0006_event_end_time_event_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='nonveg_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='₹ per non-veg plate', max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='veg_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='₹ per veg plate', max_digits=10),
        ),
    ]
