# Generated by Django 5.1.15 on 2026-07-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banquets', '0007_event_nonveg_rate_event_veg_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CateringRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veg_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nonveg_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
