# Generated by Django 5.1.15 on 2026-07-08 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_user_role_alter_userbranchaccess_role'),
        ('banquets', '0008_cateringrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionspace',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='function_spaces', to='accounts.branch'),
        ),
    ]
