# Generated by Django 5.1.15 on 2026-07-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banquets', '0009_functionspace_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='beo_no',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
