# Generated by Django 5.1.15 on 2026-07-14 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banquets', '0009_event_beo_no'),
        ('banquets', '0010_event_beo_no'),
    ]

    operations = [
    ]
