# Generated by Django 5.1.15 on 2026-08-04 09:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banquets', '0011_merge_0009_event_beo_no_0010_event_beo_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cateringrate',
            name='nonveg_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='cateringrate',
            name='veg_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='event',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='event',
            name='nonveg_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='₹ per non-veg plate', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='event',
            name='package_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='event',
            name='veg_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='₹ per veg plate', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
