# Generated by Django 5.1.15 on 2026-06-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folio',
            name='guest_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='folio',
            name='id_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='folio',
            name='id_type',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
