# Generated by Django 5.1.15 on 2026-07-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0002_folio_guest_type_folio_id_number_folio_id_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='folio',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
