# Generated by Django 5.1.15 on 2026-07-02 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('frontoffice', '0003_folio_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='folio',
            name='company',
            field=models.ForeignKey(blank=True, help_text='corporate account this BTC folio bills to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_ledger_folios', to='crm.customer'),
        ),
    ]
