# Generated by Django 5.1.15 on 2026-07-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0004_folio_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='folio',
            name='billing_mode',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
