# Generated by Django 5.1.15 on 2026-07-07 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_branch_userbranchaccess'),
        ('frontoffice', '0005_folio_billing_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='folio',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folios', to='accounts.branch'),
        ),
    ]
