# Generated by Django 5.1.15 on 2026-07-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0005_folio_billing_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='folio',
            name='id_scan',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='folio',
            name='signature',
            field=models.TextField(blank=True, default=''),
        ),
    ]
