# Generated by Django 5.1.15 on 2026-07-14 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0006_folio_id_scan_folio_signature'),
        ('frontoffice', '0006_folio_location'),
    ]

    operations = [
    ]
