# Generated by Django 5.1.4 on 2026-06-28 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=200)),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('source', models.CharField(choices=[('direct', 'Direct'), ('ota', 'OTA'), ('booking', 'Booking Engine'), ('walkin', 'Walk-in')], default='direct', max_length=20)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('in_house', 'In House'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='booked', max_length=20)),
                ('nights', models.PositiveSmallIntegerField(default=1)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prepaid', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='crm.customer')),
                ('rate_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='rooms.rateplan')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='rooms.room')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='rooms.roomtype')),
            ],
            options={
                'ordering': ['checkin_date', 'guest_name'],
            },
        ),
    ]
