# Generated by Django 5.1.15 on 2026-07-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_groupblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='channel_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='reservation',
            name='ota_ref',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
    ]
