# Generated by Django 5.1.15 on 2026-07-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_channel_name_reservation_ota_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='precheckin',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reservation',
            name='precheckin_done',
            field=models.BooleanField(default=False),
        ),
    ]
