# Generated by Django 5.1.15 on 2026-06-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_mfa_enabled_user_mfa_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='gst_billing_mode',
            field=models.CharField(default='with_gst', max_length=12),
        ),
    ]
