# Generated by Django 5.1.15 on 2026-07-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_property_gst_billing_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='property',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
