# Generated by Django 5.1.15 on 2026-07-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_property_address_property_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=40, unique=True)),
                ('modules', models.JSONField(default=list)),
            ],
        ),
    ]
