# Generated by Django 5.1.15 on 2026-07-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_roleconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='logo',
            field=models.TextField(blank=True, help_text='hotel logo as a data URL (white-label)'),
        ),
    ]
