# Generated by Django 5.1.15 on 2026-07-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_property_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Managing Director', 'Managing Director'), ('General Manager', 'General Manager'), ('Front Office', 'Front Office'), ('F&B Cashier', 'F&B Cashier'), ('Captain', 'Captain'), ('Housekeeping', 'Housekeeping')], default='Front Office', max_length=40),
        ),
    ]
