# Generated by Django 5.1.15 on 2026-07-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='doc_footer',
            field=models.TextField(blank=True, default='', help_text='terms & conditions / bank details footer'),
        ),
        migrations.AddField(
            model_name='property',
            name='doc_header',
            field=models.TextField(blank=True, default='', help_text='extra letterhead lines (tagline, CIN, FSSAI…)'),
        ),
    ]
