# Generated by Django 5.1.15 on 2026-07-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='swiggy_commission_pct',
            field=models.DecimalField(decimal_places=2, default=23, max_digits=5),
        ),
        migrations.AddField(
            model_name='property',
            name='zomato_commission_pct',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=5),
        ),
    ]
