# Generated by Django 5.1.15 on 2026-07-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_property_swiggy_commission_pct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Super Admin', 'Super Admin'), ('Admin', 'Admin'), ('Managing Director', 'Managing Director'), ('CEO', 'CEO'), ('General Manager', 'General Manager'), ('Finance', 'Finance'), ('Restaurant Manager', 'Restaurant Manager'), ('Front Office', 'Front Office'), ('F&B Cashier', 'F&B Cashier'), ('Captain', 'Captain'), ('Housekeeping', 'Housekeeping'), ('Chef / Kitchen', 'Chef / Kitchen'), ('Store Keeper', 'Store Keeper'), ('Bar Captain', 'Bar Captain')], default='Front Office', max_length=40),
        ),
    ]
