# Generated by Django 5.1.15 on 2026-07-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitlement',
            name='bar_mode',
            field=models.CharField(choices=[('separate', 'Separate operation'), ('combined', 'Combined with restaurant')], default='separate', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Super Admin', 'Super Admin'), ('Admin', 'Admin'), ('Managing Director', 'Managing Director'), ('CEO', 'CEO'), ('General Manager', 'General Manager'), ('Finance', 'Finance'), ('Restaurant Manager', 'Restaurant Manager'), ('Front Office', 'Front Office'), ('F&B Cashier', 'F&B Cashier'), ('Captain', 'Captain'), ('Housekeeping', 'Housekeeping'), ('Chef / Kitchen', 'Chef / Kitchen'), ('Store Keeper', 'Store Keeper'), ('Bar Captain', 'Bar Captain'), ('Bar Cashier', 'Bar Cashier')], default='Front Office', max_length=40),
        ),
    ]
