# Generated by Django 5.1.15 on 2026-07-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_entitlement_bar_mode_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='beo_prefix',
            field=models.CharField(default='BEO', max_length=12),
        ),
        migrations.AddField(
            model_name='property',
            name='bill_prefix',
            field=models.CharField(default='BILL', max_length=12),
        ),
        migrations.AddField(
            model_name='property',
            name='grn_prefix',
            field=models.CharField(default='GRN', max_length=12),
        ),
        migrations.AddField(
            model_name='property',
            name='invoice_prefix',
            field=models.CharField(default='HRT', max_length=12),
        ),
        migrations.AddField(
            model_name='property',
            name='po_prefix',
            field=models.CharField(default='PO', max_length=12),
        ),
    ]
