# Generated by Django 5.1.15 on 2026-07-07 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(help_text='Short code, e.g. DTN — used in invoice/table numbering', max_length=10, unique=True)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('edition', models.CharField(choices=[('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('both', 'Both')], default='both', max_length=20)),
                ('hms', models.BooleanField(default=True)),
                ('restaurant', models.BooleanField(default=True)),
                ('banquets', models.BooleanField(default=True)),
                ('rms', models.BooleanField(default=True)),
                ('invoice_prefix', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('onboarding', 'Onboarding'), ('active', 'Active'), ('closed', 'Closed')], default='onboarding', max_length=12)),
                ('logo', models.TextField(blank=True, help_text='branch logo as a data URL; falls back to the group logo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='accounts.property')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserBranchAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Super Admin', 'Super Admin'), ('Admin', 'Admin'), ('Managing Director', 'Managing Director'), ('CEO', 'CEO'), ('General Manager', 'General Manager'), ('Finance', 'Finance'), ('Restaurant Manager', 'Restaurant Manager'), ('Hotel Manager', 'Hotel Manager'), ('Front Office', 'Front Office'), ('F&B Cashier', 'F&B Cashier'), ('Captain', 'Captain'), ('Housekeeping', 'Housekeeping'), ('Chef / Kitchen', 'Chef / Kitchen'), ('Store Keeper', 'Store Keeper'), ('Bar Captain', 'Bar Captain'), ('Bar Cashier', 'Bar Cashier')], max_length=40)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, help_text='Temporary assignment — leave blank for a standing one', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_access', to='accounts.branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['branch__name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'branch', 'role'), name='unique_user_branch_role')],
            },
        ),
    ]
