# Generated by Django 5.1.15 on 2026-07-14 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_property_beo_prefix_property_bill_prefix_and_more'),
        ('accounts', '0018_property_beo_prefix_property_bill_prefix_and_more'),
    ]

    operations = [
    ]
