# Generated by Django 5.1.15 on 2026-07-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_merge_20260714_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='doc_footer_align',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=6),
        ),
        migrations.AddField(
            model_name='property',
            name='doc_header_align',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=6),
        ),
    ]
