# Generated by Django 5.1.15 on 2026-07-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_property_doc_footer_align_property_doc_header_align'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitlement',
            name='kds_partial_ready',
            field=models.BooleanField(default=False),
        ),
    ]
