# Generated by Django 5.1.15 on 2026-07-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='invoice_columns',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='pos_bill_columns',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
