# Generated by Django 5.1.15 on 2026-07-22 06:23

from django.db import migrations, models


def copy_shared_footer_to_pos(apps, schema_editor):
    """Before this migration, doc_footer/doc_footer_align (Letterhead) printed
    on both the invoice and the POS bill. Now each has its own footer — carry
    the old shared value into pos_doc_footer so already-configured properties
    don't lose their POS bill footer (e.g. FSSAI/return-policy text)."""
    Property = apps.get_model("accounts", "Property")
    for prop in Property.objects.exclude(doc_footer=""):
        prop.pos_doc_footer = prop.doc_footer
        prop.pos_doc_footer_align = prop.doc_footer_align
        prop.save(update_fields=["pos_doc_footer", "pos_doc_footer_align"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_property_invoice_columns_property_pos_bill_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='pos_doc_footer',
            field=models.TextField(blank=True, default='', help_text='POS bill footer (e.g. return policy, thank-you line)'),
        ),
        migrations.AddField(
            model_name='property',
            name='pos_doc_footer_align',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=6),
        ),
        migrations.AddField(
            model_name='property',
            name='pos_doc_header',
            field=models.TextField(blank=True, default='', help_text='extra header lines on the POS bill (e.g. FSSAI Lic. no.)'),
        ),
        migrations.AddField(
            model_name='property',
            name='pos_doc_header_align',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=6),
        ),
        migrations.RunPython(copy_shared_footer_to_pos, migrations.RunPython.noop),
    ]
