# Generated by Django 5.1.15 on 2026-07-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_property_pos_doc_footer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitlement',
            name='features',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
