# Generated by Django 5.1.15 on 2026-08-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_entitlement_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('base_role', models.CharField(blank=True, help_text="Which built-in role's behaviour this one inherits. Blank on the built-ins themselves.", max_length=40)),
                ('rank', models.PositiveSmallIntegerField(default=1, help_text='Seniority: you may only hand out roles ranked at or below your own.')),
                ('modules', models.JSONField(default=list, help_text='Module keys, or "*" for full access.')),
                ('is_system', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True, help_text="Inactive roles stay on the accounts that hold them but can't be assigned.")),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-rank', 'name'],
            },
        ),
    ]
