# Generated by Django 5.1.15 on 2026-08-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_seed_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='Front Office', max_length=40),
        ),
        migrations.AlterField(
            model_name='userbranchaccess',
            name='role',
            field=models.CharField(max_length=40),
        ),
    ]
