# Generated by Django 5.1.15 on 2026-08-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_user_role_alter_userbranchaccess_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='default_country_code',
            field=models.CharField(default='+91', help_text='dialling code prefilled in phone fields, e.g. +91', max_length=6),
        ),
    ]
