# Generated by Django 5.1.4 on 2026-06-28 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('connected', models.BooleanField(default=True)),
                ('commission_pct', models.DecimalField(decimal_places=1, default=15, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('manual', 'Manual'), ('rms', 'RMS'), ('parity', 'Parity fix')], default='manual', max_length=12)),
                ('detail', models.CharField(max_length=200)),
                ('status', models.CharField(default='synced', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='channel.channel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_rates', to='rooms.roomtype')),
            ],
            options={
                'unique_together': {('channel', 'room_type')},
            },
        ),
    ]
