# Generated by Django 5.1.15 on 2026-07-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelpush',
            name='kind',
            field=models.CharField(choices=[('manual', 'Manual'), ('rms', 'RMS'), ('parity', 'Parity fix'), ('booking', 'Inbound booking')], default='manual', max_length=12),
        ),
    ]
