# Generated by Django 5.1.15 on 2026-06-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('contact', models.CharField(blank=True, max_length=120)),
                ('payment_terms', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
