# Generated by Django 5.1.15 on 2026-07-07 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_branch_userbranchaccess'),
        ('procurement', '0002_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='accounts.branch'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=160),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(condition=models.Q(('location__isnull', True)), fields=('name',), name='unique_supplier_name_no_location'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(condition=models.Q(('location__isnull', False)), fields=('location', 'name'), name='unique_supplier_name_with_location'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(condition=models.Q(('location__isnull', True)), fields=('name',), name='unique_vendor_name_no_location'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(condition=models.Q(('location__isnull', False)), fields=('location', 'name'), name='unique_vendor_name_with_location'),
        ),
    ]
