# Generated by Django 5.1.15 on 2026-07-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_purchaseorder_location_supplier_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='grn_no',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='po_no',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
