# Generated by Django 5.1.15 on 2026-07-14 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_goodsreceipt_grn_no_purchaseorder_po_no'),
        ('procurement', '0004_goodsreceipt_grn_no_purchaseorder_po_no'),
    ]

    operations = [
    ]
