# Generated by Django 5.1.15 on 2026-07-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_merge_20260714_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='bill_image',
            field=models.TextField(blank=True, default=''),
        ),
    ]
