# Generated by Django 5.1.15 on 2026-07-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_goodsreceipt_bill_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='requested_by',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
