# Generated by Django 5.1.15 on 2026-07-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_seed'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('mode', models.CharField(choices=[('kds', 'Kitchen Display'), ('print', 'Print only')], default='kds', max_length=6)),
                ('is_bar', models.BooleanField(default=False, help_text='drives MenuItem.bar_menu auto-assignment')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-is_bar', 'name'],
            },
        ),
    ]
