# Generated by Django 5.1.15 on 2026-07-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='code',
            field=models.CharField(blank=True, default='', help_text='raw material code, e.g. RM-0001', max_length=20),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='earliest expiry in stock, where applicable', null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='min_stock_level',
            field=models.DecimalField(decimal_places=3, default=0, help_text='hard floor — running out stops prep', max_digits=12),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='storage_location',
            field=models.CharField(blank=True, default='', help_text='storage location / warehouse', max_length=80),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=0, help_text='stock balance after this movement', max_digits=12),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram (KG)'), ('g', 'Gram (GM)'), ('l', 'Litre (L)'), ('ml', 'Millilitre (ML)'), ('pc', 'Piece (Nos)'), ('pkt', 'Packet')], default='kg', help_text='base consumption unit', max_length=12),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='purchase rate per base unit', max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='kind',
            field=models.CharField(choices=[('receipt', 'Purchase Receipt'), ('transfer', 'Stock Transfer'), ('production', 'Production / Preparation'), ('consumption', 'Recipe Consumption'), ('wastage', 'Wastage'), ('adjustment', 'Stock Adjustment'), ('return', 'Stock Return'), ('count', 'Physical Stock Count'), ('expiry', 'Expiry / Damage Loss')], max_length=14),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='source',
            field=models.CharField(blank=True, help_text='reference: purchase bill / order / transfer no.', max_length=80),
        ),
    ]
