# Generated by Django 5.1.15 on 2026-07-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_ingredient_code_ingredient_expiry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name_plural': 'ingredient categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Uom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'unit of measurement',
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(default='kg', help_text='base consumption unit', max_length=12),
        ),
    ]
