# Generated by Django 5.1.15 on 2026-07-07 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_branch_userbranchaccess'),
        ('inventory', '0004_seed_masters'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='accounts.branch'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(condition=models.Q(('location__isnull', True)), fields=('name',), name='unique_ingredient_name_no_location'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(condition=models.Q(('location__isnull', False)), fields=('location', 'name'), name='unique_ingredient_name_with_location'),
        ),
    ]
