# Generated by Django 5.1.15 on 2026-06-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostFoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('handler', models.CharField(blank=True, max_length=120)),
                ('guest_contact', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('stored', 'Stored'), ('claimed', 'Claimed'), ('disposed', 'Disposed')], default='stored', max_length=12)),
                ('found_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-found_at'],
            },
        ),
    ]
