# Generated by Django 5.1.4 on 2026-06-28 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recommended_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(max_length=200)),
                ('demand_index', models.PositiveSmallIntegerField(default=50, help_text='0-100 demand signal')),
                ('status', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed')], default='open', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_recs', to='rooms.roomtype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
