# Generated by Django 5.1.15 on 2026-06-29 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_los', models.PositiveSmallIntegerField(default=1, help_text='minimum length of stay')),
                ('cta', models.BooleanField(default=False, help_text='closed to arrival')),
                ('ctd', models.BooleanField(default=False, help_text='closed to departure')),
                ('stop_sell', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restriction', to='rooms.roomtype')),
            ],
        ),
    ]
