# Generated by Django 5.1.4 on 2026-06-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('locality', models.CharField(blank=True, max_length=120)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('customer_type', models.CharField(choices=[('guest', 'Guest'), ('corporate', 'Corporate'), ('agent', 'Travel Agent')], default='guest', max_length=20)),
                ('btc_enabled', models.BooleanField(default=False, help_text='Bill-to-company / credit')),
                ('outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loyalty_points', models.IntegerField(default=0)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
