# Generated by Django 5.1.15 on 2026-07-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('channel', models.CharField(default='sms', help_text='sms | whatsapp', max_length=12)),
                ('segment', models.CharField(default='all', help_text='all | guests | corporate | loyal', max_length=20)),
                ('message', models.CharField(help_text='{name} and {points} placeholders', max_length=480)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0, help_text='no consent / no mobile')),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
