# Generated by Django 5.1.15 on 2026-07-20 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('points_cost', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('percent', 'Percent off'), ('fixed', 'Fixed amount off')], default='fixed', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('redeemed_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['points_cost'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('min_lifetime_points', models.PositiveIntegerField(default=0)),
                ('earn_multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['min_lifetime_points'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='anniversary_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='lifetime_points',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LoyaltyLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('earn', 'Earned'), ('redeem', 'Redeemed'), ('bonus', 'Bonus')], max_length=10)),
                ('points', models.IntegerField(help_text='positive for earn/bonus, negative for redeem')),
                ('balance_after', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_ledger', to='crm.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyGreetingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion', models.CharField(help_text='birthday | anniversary', max_length=20)),
                ('sent_on', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='greeting_logs', to='crm.customer')),
            ],
            options={
                'unique_together': {('customer', 'occasion', 'sent_on')},
            },
        ),
    ]
