# Generated by Django 5.1.15 on 2026-08-04 09:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_seed_base_loyalty_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltyreward',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='loyaltytier',
            name='earn_multiplier',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
