# Generated by Django 5.1.4 on 2026-06-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('department', models.CharField(max_length=80)),
                ('role', models.CharField(max_length=80)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('shifts', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
            options={
                'ordering': ['department', 'name'],
            },
        ),
    ]
