# Generated by Django 5.1.15 on 2026-07-07 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_branch_userbranchaccess'),
        ('hr', '0002_employee_monthly_salary_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Home branch for attendance/payroll/rostering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Linked login, if this person has system access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_record', to=settings.AUTH_USER_MODEL),
        ),
    ]
