# Generated by Django 5.1.15 on 2026-07-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_leavetype_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='manager_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='manager_decided_by',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('manager_approved', 'Manager approved'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
