# Generated by Django 5.1.15 on 2026-07-08 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_leaverequest_manager_decided_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('paid', 'Paid')], default='draft', max_length=10)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_by', models.CharField(blank=True, max_length=120)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('paid_by', models.CharField(blank=True, max_length=120)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_in_month', models.PositiveIntegerField()),
                ('payable_days', models.DecimalField(decimal_places=1, max_digits=4)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('basic', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hra', models.DecimalField(decimal_places=2, max_digits=12)),
                ('other_allowance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gross_earned', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pf', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('esi', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adjustment_note', models.CharField(blank=True, max_length=200)),
                ('net', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='hr.employee')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slips', to='hr.payrollrun')),
            ],
            options={
                'ordering': ['employee__department', 'employee__name'],
                'unique_together': {('run', 'employee')},
            },
        ),
    ]
