# Generated by Django 5.1.15 on 2026-07-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_payrollrun_payslip'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='statutory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='wage_type',
            field=models.CharField(choices=[('monthly', 'Monthly salary'), ('daily', 'Daily wage')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='statutory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='wage_type',
            field=models.CharField(default='monthly', max_length=10),
        ),
    ]
