# Generated by Django 5.1.15 on 2026-07-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_employee_daily_rate_employee_statutory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='has_allowances',
            field=models.BooleanField(default=True),
        ),
    ]
