# Generated by Django 5.1.15 on 2026-07-08 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_employee_has_allowances'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='advance_recovery',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='SalaryAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('advance', 'Advance'), ('loan', 'Loan')], default='advance', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_installment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('recovered', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(default='active', max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('issued_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='hr.employee')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvanceRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoveries', to='hr.payslip')),
                ('advance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_lines', to='hr.salaryadvance')),
            ],
            options={
                'unique_together': {('payslip', 'advance')},
            },
        ),
    ]
