# Generated by Django 5.1.15 on 2026-07-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='country_code',
            field=models.CharField(default='+91', max_length=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='weekly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='wage_type',
            field=models.CharField(choices=[('monthly', 'Monthly salary'), ('daily', 'Daily wage'), ('weekly', 'Weekly wage')], default='monthly', max_length=10),
        ),
    ]
