# Generated by Django 5.1.15 on 2026-08-04 09:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matreq', '0002_materialrequest_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrequestline',
            name='qty',
            field=models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
