# Generated by Django 5.1.15 on 2026-06-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GstSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('rate', models.DecimalField(decimal_places=1, max_digits=4)),
                ('hsn_sac', models.CharField(blank=True, max_length=12)),
                ('applies_to', models.CharField(blank=True, help_text='rooms | fnb | banquet | service', max_length=40)),
            ],
            options={
                'ordering': ['rate'],
            },
        ),
    ]
