# Generated by Django 5.1.4 on 2026-06-28 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_occupancy', models.PositiveSmallIntegerField(default=2)),
                ('gst_slab', models.DecimalField(decimal_places=1, default=12, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='RatePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inclusions', models.CharField(blank=True, max_length=200)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_plans', to='rooms.roomtype')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=12)),
                ('branch', models.CharField(default='Main', max_length=80)),
                ('floor', models.PositiveSmallIntegerField(default=1)),
                ('view', models.CharField(blank=True, max_length=40)),
                ('smoking', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('vacant_clean', 'Vacant / Clean'), ('vacant_dirty', 'Vacant / Dirty'), ('occupied', 'Occupied'), ('cleaning', 'Cleaning'), ('inspected', 'Inspected'), ('ooo', 'Out of Order')], default='vacant_clean', max_length=20)),
                ('ooo_reason', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='rooms.roomtype')),
            ],
            options={
                'ordering': ['branch', 'number'],
                'unique_together': {('branch', 'number')},
            },
        ),
    ]
