# Generated by Django 5.1.15 on 2026-07-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='cleaning_note',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='room',
            name='cleaning_requested',
            field=models.BooleanField(default=False),
        ),
    ]
