# Generated by Django 5.1.15 on 2026-07-07 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_branch_userbranchaccess'),
        ('rooms', '0002_room_cleaning_note_room_cleaning_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='location',
            field=models.ForeignKey(blank=True, help_text="Which of the group's branches this room belongs to", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='accounts.branch'),
        ),
        migrations.AlterField(
            model_name='room',
            name='branch',
            field=models.CharField(default='Main', help_text='Building/wing label within this location, e.g. Main vs Annexe', max_length=80),
        ),
    ]
