# Generated by Django 5.1.15 on 2026-07-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_branch_userbranchaccess'),
        ('rooms', '0003_room_location_alter_room_branch'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(condition=models.Q(('location__isnull', True)), fields=('branch', 'number'), name='unique_room_no_location'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(condition=models.Q(('location__isnull', False)), fields=('location', 'branch', 'number'), name='unique_room_with_location'),
        ),
    ]
