# Generated by Django 5.1.15 on 2026-08-04 10:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_rateplan_rate_alter_roomtype_base_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='gst_slab',
            field=models.DecimalField(decimal_places=1, default=12, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
    ]
