# Generated by Django 5.1.15 on 2026-06-30 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('pos', '0009_order_brand_menuschedule'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeline',
            name='sub_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_in_recipes', to='pos.menuitem'),
        ),
        migrations.AlterField(
            model_name='recipeline',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipe_lines', to='inventory.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipeline',
            name='qty',
            field=models.DecimalField(decimal_places=3, help_text='per single dish', max_digits=10),
        ),
    ]
