# Generated by Django 5.1.15 on 2026-07-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipeline_sub_recipe_alter_recipeline_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeline',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='recipeline',
            name='wastage_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
