# Generated by Django 5.1.15 on 2026-07-02 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_kot_ready_at_kot_served_at_menuitem_image_and_more'),
        ('recipes', '0003_recipeline_unit_recipeline_wastage_pct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produced_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_batches', to='pos.menuitem')),
            ],
            options={
                'verbose_name_plural': 'production batches',
                'ordering': ['-created_at'],
            },
        ),
    ]
