# Generated by Django 5.1.4 on 2026-06-28 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('frontoffice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('section', models.CharField(default='Main', max_length=40)),
                ('seats', models.PositiveSmallIntegerField(default=4)),
                ('shape', models.CharField(default='square', max_length=20)),
                ('status', models.CharField(choices=[('free', 'Free'), ('running', 'Running'), ('printed', 'Printed'), ('paid', 'Paid'), ('reserved', 'Reserved')], default='free', max_length=12)),
            ],
            options={
                'ordering': ['section', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('short_code', models.CharField(blank=True, max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_rate', models.DecimalField(decimal_places=1, default=5, max_digits=4)),
                ('diet', models.CharField(choices=[('veg', 'Veg'), ('nonveg', 'Non-veg'), ('egg', 'Egg')], default='veg', max_length=10)),
                ('station', models.CharField(default='kitchen', help_text='kitchen | bar', max_length=20)),
                ('available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='pos.category')),
            ],
            options={
                'ordering': ['category__sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('dinein', 'Dine-in'), ('takeaway', 'Takeaway'), ('delivery', 'Delivery')], default='dinein', max_length=12)),
                ('covers', models.PositiveSmallIntegerField(default=1)),
                ('captain', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('open', 'Open'), ('kot_fired', 'KOT Fired'), ('billed', 'Billed'), ('settled', 'Settled'), ('posted_to_room', 'Posted to Room')], default='open', max_length=20)),
                ('kot_no', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='crm.customer')),
                ('folio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_orders', to='frontoffice.folio')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='pos.table')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveSmallIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=120)),
                ('kot_fired', models.BooleanField(default=False)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pos.order')),
            ],
        ),
    ]
