# Generated by Django 5.1.15 on 2026-06-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_orderline_addons_addongroup_addon_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_uuid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='offline_origin',
            field=models.BooleanField(default=False),
        ),
    ]
