# Generated by Django 5.1.15 on 2026-06-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_order_client_uuid_order_offline_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kitchen_status',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
