# Generated by Django 5.1.15 on 2026-06-29 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_order_kitchen_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(help_text='dinein | takeaway | delivery | online', max_length=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_prices', to='pos.menuitem')),
            ],
            options={
                'unique_together': {('menu_item', 'channel')},
            },
        ),
    ]
