# Generated by Django 5.1.15 on 2026-06-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_channelprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='external_ref',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='online_status',
            field=models.CharField(blank=True, default='', help_text='received | accepted | ready | dispatched', max_length=12),
        ),
        migrations.AddField(
            model_name='order',
            name='prepaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='source_platform',
            field=models.CharField(blank=True, default='', help_text='zomato | swiggy | website | qr', max_length=20),
        ),
    ]
