# Generated by Django 5.1.15 on 2026-06-30 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_order_external_ref_order_online_status_order_prepaid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveSmallIntegerField(default=1)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_components', to='pos.menuitem')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_combos', to='pos.menuitem')),
            ],
        ),
    ]
