# Generated by Django 5.1.15 on 2026-06-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_order_brand_menuschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='qr_token',
            field=models.CharField(blank=True, db_index=True, default='', help_text='token embedded in the table QR for guest ordering', max_length=20),
        ),
    ]
