# Generated by Django 5.1.15 on 2026-07-02 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_kot_orderline_kot'),
    ]

    operations = [
        migrations.CreateModel(
            name='TillSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_by', models.CharField(blank=True, max_length=80)),
                ('opening_float', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(default='open', max_length=8)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.CharField(blank=True, max_length=80)),
                ('counted_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expected_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('denominations', models.JSONField(blank=True, default=dict, help_text='{"500": 4, "100": 10, ...} counted notes')),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='token_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=40, unique=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='1–5 stars', null=True)),
                ('nps', models.PositiveSmallIntegerField(blank=True, help_text='0–10 recommend score', null=True)),
                ('comment', models.CharField(blank=True, max_length=400)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='pos.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TableReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='reservation', help_text='reservation | waitlist', max_length=12)),
                ('name', models.CharField(max_length=80)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('party_size', models.PositiveSmallIntegerField(default=2)),
                ('reserved_for', models.DateTimeField(blank=True, help_text='null for waitlist', null=True)),
                ('status', models.CharField(default='booked', max_length=12)),
                ('note', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='pos.table')),
            ],
            options={
                'ordering': ['reserved_for', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TillEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(help_text='in | out', max_length=4)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=160)),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='pos.tillsession')),
            ],
            options={
                'verbose_name_plural': 'till entries',
                'ordering': ['created_at'],
            },
        ),
    ]
