# Generated by Django 5.1.15 on 2026-07-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_kot_ready_at_kot_served_at_menuitem_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mode',
            field=models.CharField(choices=[('dinein', 'Dine-in'), ('takeaway', 'Takeaway'), ('delivery', 'Delivery'), ('room', 'Room')], default='dinein', max_length=12),
        ),
    ]
