# Generated by Django 5.1.15 on 2026-07-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_alter_order_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=10),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='approved_by',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='reject_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
