# Generated by Django 5.1.15 on 2026-07-04 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_menuitem_approval_status_menuitem_approved_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('section', models.CharField(default='Bar', max_length=40)),
                ('seats', models.PositiveSmallIntegerField(default=4)),
                ('shape', models.CharField(default='square', max_length=20)),
                ('status', models.CharField(choices=[('free', 'Free'), ('running', 'Running'), ('paid', 'Paid')], default='free', max_length=12)),
            ],
            options={
                'ordering': ['section', 'name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='department',
            field=models.CharField(choices=[('food', 'Food'), ('bar', 'Bar')], default='food', max_length=6),
        ),
        migrations.AddField(
            model_name='order',
            name='bar_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='pos.bartable'),
        ),
    ]
