# Generated by Django 5.1.15 on 2026-07-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_bartable_order_department_order_bar_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='bar_menu',
            field=models.BooleanField(default=False),
        ),
    ]
