# Generated by Django 5.1.15 on 2026-07-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0017_menuitem_bar_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_bar',
            field=models.BooleanField(default=False),
        ),
    ]
