# Generated by Django 5.1.15 on 2026-07-07 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_branch_userbranchaccess'),
        ('pos', '0018_category_is_bar'),
    ]

    operations = [
        migrations.AddField(
            model_name='bartable',
            name='location',
            field=models.ForeignKey(blank=True, help_text="Which of the group's branches this bar table belongs to", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bar_tables', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='table',
            name='location',
            field=models.ForeignKey(blank=True, help_text="Which of the group's branches this table belongs to", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tables', to='accounts.branch'),
        ),
        migrations.AddConstraint(
            model_name='bartable',
            constraint=models.UniqueConstraint(fields=('location', 'name'), name='unique_bartable_name_per_location'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(fields=('location', 'name'), name='unique_table_name_per_location'),
        ),
    ]
