# Generated by Django 5.1.15 on 2026-07-09 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0020_category_location_menuitem_location_order_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='assigned_captain',
            field=models.ForeignKey(blank=True, help_text='Captain this table is assigned to — set by the F&B Cashier running the floor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tables', to=settings.AUTH_USER_MODEL),
        ),
    ]
