# Generated by Django 5.1.15 on 2026-07-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0021_table_assigned_captain'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='floor',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
