# Generated by Django 5.1.15 on 2026-07-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0023_backfill_table_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bill_no',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
