# Generated by Django 5.1.15 on 2026-07-14 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0019_order_bill_no'),
        ('pos', '0024_order_bill_no'),
    ]

    operations = [
    ]
