# Generated by Django 5.1.15 on 2026-07-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0025_merge_0019_order_bill_no_0024_order_bill_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
