# Generated by Django 5.1.15 on 2026-07-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0026_orderline_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='kot',
            name='station',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
