# Generated by Django 5.1.15 on 2026-07-20 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_seed_base_loyalty_tier'),
        ('pos', '0027_kot_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='loyalty_reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.loyaltyreward'),
        ),
        migrations.AlterField(
            model_name='order',
            name='loyalty_redeemed',
            field=models.PositiveIntegerField(default=0, help_text='rupee-equivalent discount applied'),
        ),
    ]
