# Generated by Django 5.1.15 on 2026-07-23 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_property_pos_doc_footer_and_more'),
        ('pos', '0028_order_loyalty_reward_alter_order_loyalty_redeemed'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatorConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('zomato', 'Zomato'), ('swiggy', 'Swiggy')], max_length=20)),
                ('outlet_id', models.CharField(help_text="This outlet's ID on the aggregator's side", max_length=80)),
                ('webhook_secret_encrypted', models.TextField()),
                ('connected', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text="Which branch this outlet's orders belong to — blank for a single-outlet property", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aggregator_connections', to='accounts.branch')),
            ],
            options={
                'unique_together': {('platform', 'branch')},
            },
        ),
    ]
