# Generated by Django 5.1.15 on 2026-08-04 10:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0030_alter_addon_price_alter_channelprice_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
